# Generated by Django 5.1.7 on 2025-05-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.application'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('sender', 'receiver')},
        ),
    ]
