import { StyleSheet } from "react-native";

const AdminCompanyStyles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: "#fff" },
  header: { fontSize: 22, fontWeight: "bold", marginBottom: 16 },
  container: {
    padding: 16,
    backgroundColor: "#f9f9f9",
    flex: 1,
  },
  header: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
    color: "#333",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#007bff",
  },
  text: {
    fontSize: 14,
    marginBottom: 2,
    color: "#333",
  },
  deleteButton: {
    marginTop: 12,
    backgroundColor: "#ff4d4d",
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: "center",
  },
  deleteText: {
    color: "#fff",
    fontWeight: "bold",
  },
  centered: {
    marginTop: 20,
    textAlign: "center",
  },
  errorText: {
    color: "red",
  },
  noData: {
    textAlign: "center",
    color: "#666",
    marginTop: 20,
  },
  card: {
    padding: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    marginBottom: 12,
    backgroundColor: "#f8f8f8",
    elevation: 2,
  },
  title: { fontSize: 18, fontWeight: "bold", marginBottom: 6 },
  websiteLink: {
    color: "blue",
    textDecorationLine: "underline",
    marginBottom: 4,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    gap: 8,
  },
  errorText: {
    color: "red",
    marginTop: 20,
    textAlign: "center",
  },
  container: {
    padding: 16,
    backgroundColor: "#f0f2f5",
    flex: 1,
  },
  link: {
    color: "#1890ff",
    textDecorationLine: "underline",
  },
  header: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 16,
    color: "#333",
  },
  card: {
    backgroundColor: "#ffffff",
    padding: 16,
    marginBottom: 12,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  title: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#1890ff",
    flex: 1,
    marginRight: 8,
  },
  text: {
    fontSize: 14,
    marginBottom: 4,
    color: "#333",
  },
  container: {
    padding: 16,
    backgroundColor: "#f9f9f9",
    flex: 1,
  },
  header: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
    color: "#333",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignSelf: "center",
    marginBottom: 10,
  },
  name: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 6,
    textAlign: "center",
    color: "#007bff",
  },
  text: {
    fontSize: 14,
    marginBottom: 2,
    color: "#333",
  },
  deleteButton: {
    marginTop: 12,
    backgroundColor: "#ff4d4d",
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: "center",
  },
  deleteText: {
    color: "#fff",
    fontWeight: "bold",
  },
  centered: {
    marginTop: 20,
    textAlign: "center",
  },
  errorText: {
    color: "red",
  },
  noData: {
    textAlign: "center",
    color: "#666",
    marginTop: 20,
  },
  container: {
    padding: 16,
    backgroundColor: "#f9f9f9",
    flex: 1,
  },
  header: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
    color: "#333",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#007bff",
  },
  text: {
    fontSize: 14,
    marginBottom: 2,
    color: "#333",
  },
  noData: {
    textAlign: "center",
    color: "#666",
    marginTop: 20,
  },
});
export default AdminCompanyStyles;
